"""
Streamlit UI for the Heart Disease Prediction pipeline.

Run locally with:
    streamlit run ui/app.py
"""

import os
import joblib
import numpy as np
import pandas as pd
import streamlit as st

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MODEL_PATH = os.path.join(BASE_DIR, "models", "final_model.pkl")
COLUMNS_PATH = os.path.join(BASE_DIR, "models", "feature_columns.pkl")
SCALER_PATH = os.path.join(BASE_DIR, "models", "scaler.pkl")
DATA_PATH = os.path.join(BASE_DIR, "data", "heart_disease.csv")

st.set_page_config(page_title="Heart Disease Risk Predictor", page_icon="\u2764\ufe0f", layout="centered")

st.title("\u2764\ufe0f Heart Disease Risk Predictor")
st.caption(
    "Educational demo built on the Heart Disease UCI dataset. "
    "This is not a medical diagnostic tool."
)


@st.cache_resource
def load_artifacts():
    model = joblib.load(MODEL_PATH)
    feature_columns = joblib.load(COLUMNS_PATH)
    scaler = joblib.load(SCALER_PATH)
    return model, feature_columns, scaler


try:
    model, feature_columns, scaler = load_artifacts()
except FileNotFoundError:
    st.error(
        "Model artifacts not found. Run `python run_pipeline.py` first "
        "to train the model and generate models/final_model.pkl."
    )
    st.stop()

numeric_cols = ["age", "trestbps", "chol", "thalach", "oldpeak"]

st.subheader("Enter patient data")

col1, col2 = st.columns(2)
with col1:
    age = st.number_input("Age", 20, 100, 50)
    sex = st.selectbox("Sex", options=[("Male", 1), ("Female", 0)], format_func=lambda x: x[0])[1]
    cp = st.selectbox(
        "Chest Pain Type",
        options=[(0, "Typical angina"), (1, "Atypical angina"), (2, "Non-anginal pain"), (3, "Asymptomatic")],
        format_func=lambda x: x[1],
    )[0]
    trestbps = st.number_input("Resting Blood Pressure (mm Hg)", 80, 220, 120)
    chol = st.number_input("Serum Cholesterol (mg/dl)", 100, 600, 200)
    fbs = st.selectbox("Fasting Blood Sugar > 120 mg/dl", options=[("No", 0), ("Yes", 1)], format_func=lambda x: x[0])[1]
    restecg = st.selectbox(
        "Resting ECG Result",
        options=[(0, "Normal"), (1, "ST-T abnormality"), (2, "LV hypertrophy")],
        format_func=lambda x: x[1],
    )[0]

with col2:
    thalach = st.number_input("Max Heart Rate Achieved", 60, 220, 150)
    exang = st.selectbox("Exercise-Induced Angina", options=[("No", 0), ("Yes", 1)], format_func=lambda x: x[0])[1]
    oldpeak = st.number_input("ST Depression (oldpeak)", 0.0, 7.0, 1.0, step=0.1)
    slope = st.selectbox(
        "Slope of Peak Exercise ST Segment",
        options=[(0, "Upsloping"), (1, "Flat"), (2, "Downsloping")],
        format_func=lambda x: x[1],
    )[0]
    ca = st.selectbox("Number of Major Vessels (0-4)", options=[0, 1, 2, 3, 4])
    thal = st.selectbox(
        "Thalassemia",
        options=[(1, "Normal"), (2, "Fixed defect"), (3, "Reversible defect")],
        format_func=lambda x: x[1],
    )[0]

if st.button("Predict", type="primary"):
    raw_input = pd.DataFrame([{
        "age": age, "sex": sex, "cp": cp, "trestbps": trestbps, "chol": chol,
        "fbs": fbs, "restecg": restecg, "thalach": thalach, "exang": exang,
        "oldpeak": oldpeak, "slope": slope, "ca": ca, "thal": thal,
    }])

    categorical_cols = ["cp", "restecg", "slope", "thal", "ca"]
    encoded = pd.get_dummies(raw_input, columns=categorical_cols)

    # Scale ALL numeric columns first (the scaler was fit on all 5 of them,
    # even though feature selection later dropped some from the final model)
    raw_input_scaled = raw_input.copy()
    raw_input_scaled[numeric_cols] = scaler.transform(raw_input[numeric_cols])

    # Align to the exact columns the model was trained on
    input_row = pd.DataFrame(0.0, index=[0], columns=feature_columns)
    for col in encoded.columns:
        if col in input_row.columns and col not in numeric_cols:
            input_row[col] = encoded[col].values
    for col in numeric_cols:
        if col in input_row.columns:
            input_row[col] = raw_input_scaled[col].values

    pred = model.predict(input_row)[0]
    proba = model.predict_proba(input_row)[0][1] if hasattr(model, "predict_proba") else None

    st.divider()
    if pred == 1:
        st.error(f"⚠️ Higher predicted risk of heart disease.")
    else:
        st.success(f"✅ Lower predicted risk of heart disease.")

    if proba is not None:
        st.metric("Predicted probability of heart disease", f"{proba:.1%}")

    st.caption(
        "This prediction is generated by a machine learning model trained on the "
        "Heart Disease UCI dataset for educational purposes only. It is not a "
        "substitute for professional medical advice, diagnosis, or treatment."
    )

st.divider()
with st.expander("About this app"):
    st.write(
        "This app loads a trained scikit-learn pipeline (see `models/final_model.pkl`) "
        "produced by the notebooks in `notebooks/` and `run_pipeline.py`. "
        "The model was trained on the Heart Disease UCI dataset (303 patient records, "
        "13 clinical features)."
    )
